Create silence and unsilence command
Kotlin-Discord/bot pull request #18
Opened 2020-08-27 12:44 UTC by ks129

Created commands for channel silencing and unsilencing. Supports both timed silencing and permanent silencing.

2020-08-27 13:12 UTC, Akarys42 requested changes
It looks pretty good so far. The main issue right now is that the bot will let you silence channels in which `@Developer` doesn't have any permission, or send is explicitly denied, the bot should instead send an error message.

2020-08-28 17:36 UTC, gdude2002 commented on src/main/kotlin/com/kotlindiscord/bot/extensions/SilenceExtension.kt
> +            name = "silence"
We do not.

2020-08-28 17:37 UTC, gdude2002 commented on src/main/kotlin/com/kotlindiscord/bot/extensions/SilenceExtension.kt
> +            name = "unsilence"
Nop, no hide pls.

2021-03-24 11:09 UTC, gdude2002 commented
While I appreciate the work done on this, and it's not your fault that bot development stalled (ultimately I just had far too much to do), I now have a better understanding of how to write this type of extension - and the bot needs to be updated to the latest version of the framework before any more development can continue, so it would be best to close this now and rewrite it later on.

Even so, thanks for spending time on this!

2021-03-24 11:09 UTC, closed without merging